/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dev.core;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class EmployeeTest {
    @Test 
    public void testEmployee() {
    	final String name = "Dev";
    	final String position = "Developer";
    	
        Employee employee = new Employee(name, position);
        TimeSheetReport report = new TimeSheetReport();
        assertEquals(name + " " + position, report.print(employee));
    }
}
