/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dev.core;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeTest {
    @Test 
    public void testAppHasAGreeting() {
    	final String name = "Dev";
    	final String position = "Developer";
    	
        Employee employee = new Employee(name, position);
        assertNotNull(name + " " + position, employee.printTimeSheetReport());
    }
}
